### PR TITLE
Adding gen2 s3 benchmark changes

### PR DESCRIPTION
**Pull request by nsarras**

### CODE REVIEW

**Review by velomatt — CHANGES_REQUESTED** [review]
Need the following changes:

- delete pre-built s3-benchmark
- modify s3-benchmark readme to explain how to build (clone/build dss-sdk, install yum deps, etc) - while you're at it, I just noticed there are internal URLs mentioned in that readme that need to be removed...

**Comment by nsarras** [comment]
@velomatt README files are updated and removal of binary is done in a separate repository as part of MINIO build script https://github.com/OpenMPDK/dss-minio/pull/16

**Review by velomatt — APPROVED** [review]
Tested end-to-end. Approved

**Review by snubatreus — APPROVED** [review]
Looks good 👍

**Pull request merged**
